name: running_community_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^6.1.2
  flutter_svg: ^2.0.9
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  fluttertoast: ^8.2.4
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  video_player: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  assets_gen: 1.5.0

assets_gen:
  output: utils/app_assets.dart
  class_name: AppAssets
  enable: true
  gen_package_path: false
  ignore_resolution: false
  omit_path_levels: 2
  exclude:
     
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
